trigger:
- main

pool:
  name: Default

variables:
  # Definir variables para la pipeline
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        python setup.py build
      displayName: 'Build the application'

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: Test
    displayName: 'Test Job'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        source venv/bin/activate
        pytest
      displayName: 'Run unit tests'

- stage: Publish
  displayName: 'Publish Stage'
  jobs:
  - job: Publish
    displayName: 'Publish Job'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        source venv/bin/activate
        python setup.py sdist bdist_wheel
      displayName: 'Create artifact'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
      displayName: 'Publish Artifact'
